# Generated by Django 4.0 on 2023-12-06 02:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0008_alter_interestrate_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Principal')),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Service Charge')),
                ('advance_interest', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Advance Interest')),
                ('net_proceeds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Proceeds')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RENEWED', 'Renewed'), ('REDEEMED', 'Redeemed'), ('MATURED', 'Matured'), ('EXPIRED', 'Expired'), ('AUCTIONED', 'Auctioned')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('status_updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.client')),
            ],
            managers=[
                ('Inventory', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPawn',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, editable=False)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Principal')),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Service Charge')),
                ('advance_interest', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Advance Interest')),
                ('net_proceeds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Proceeds')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RENEWED', 'Renewed'), ('REDEEMED', 'Redeemed'), ('MATURED', 'Matured'), ('EXPIRED', 'Expired'), ('AUCTIONED', 'Auctioned')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('status_updated_on', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
            ],
            options={
                'verbose_name': 'historical pawn',
                'verbose_name_plural': 'historical pawns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
