# Generated by Django 4.0 on 2023-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pawn',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='historicalpawn',
            name='status_updated_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='status_updated_on',
            field=models.DateTimeField(),
        ),
    ]
