# Generated by Django 4.0 on 2023-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0003_alter_historicalpawn_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpawn',
            name='status_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='status_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
