# Generated by Django 4.0 on 2024-01-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0005_alter_historicalpawn_advance_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
    ]
