# Generated by Django 4.0 on 2024-02-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_branch_options_alter_expensecategory_options'),
        ('pawn', '0006_remove_payment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpawn',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.branch'),
        ),
        migrations.AddField(
            model_name='pawn',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pawn_branch', to='files.branch'),
        ),
    ]
