# Generated by Django 4.0 on 2024-02-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_hub', '0001_initial'),
        ('pawn', '0007_historicalpawn_branch_pawn_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
        migrations.AddField(
            model_name='payment',
            name='cashier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='payment_cashier', to='access_hub.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_for_principal',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name='Paid for Principal'),
            preserve_default=False,
        ),
    ]
