# Generated by Django 4.0 on 2024-02-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0008_remove_payment_balance_payment_cashier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pawn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_pawn', to='pawn.pawn'),
        ),
    ]
