# Generated by Django 4.0 on 2024-02-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0009_alter_payment_pawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpawn',
            name='renewed_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pawn.pawn'),
        ),
        migrations.AddField(
            model_name='pawn',
            name='renewed_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pawn_renewed_to', to='pawn.pawn'),
        ),
        migrations.AlterField(
            model_name='historicalpawn',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RENEWED', 'Renewed'), ('REDEEMED', 'Redeemed'), ('AUCTIONED', 'Auctioned')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RENEWED', 'Renewed'), ('REDEEMED', 'Redeemed'), ('AUCTIONED', 'Auctioned')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
    ]
