# Generated by Django 4.0 on 2024-03-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0012_discountrequests_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpawn',
            name='carat',
            field=models.CharField(choices=[('10k', '10k'), ('12k', '12k'), ('18k', '18k'), ('21k', '21k'), ('24k', '24k')], default='10k', max_length=10, verbose_name='Carat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpawn',
            name='color',
            field=models.CharField(choices=[('White Gold', 'White Gold'), ('Yellow Gold', 'Yellow Gold'), ('Rose Gold', 'Rose Gold'), ('Saudi Gold', 'Saudi Gold'), ('Japan Gold', 'Japan Gold'), ('Tri-Color', 'Tri-Color')], default='White Gold', max_length=20, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpawn',
            name='grams',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Grams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpawn',
            name='item_description',
            field=models.CharField(choices=[('Anklet', 'Anklet'), ('Bangle', 'Bangle'), ('Bracelet', 'Bracelet'), ('Stud Earrings', 'Stud Earrings'), ('Loop Earrings', 'Loop Earrings'), ('Clip Earrings', 'Clip Earrings'), ('Stud Earrings', 'Stud Earrings'), ('Dangling Earrings', 'Dangling Earrings'), ('Ring', 'Ring'), ('Wedding Ring', 'Wedding Ring'), ('Necklace', 'Necklace'), ('Pendant', 'Pendant')], default='Ring', max_length=20, verbose_name='Item Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpawn',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='pawn',
            name='carat',
            field=models.CharField(choices=[('10k', '10k'), ('12k', '12k'), ('18k', '18k'), ('21k', '21k'), ('24k', '24k')], default='10k', max_length=10, verbose_name='Carat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawn',
            name='color',
            field=models.CharField(choices=[('White Gold', 'White Gold'), ('Yellow Gold', 'Yellow Gold'), ('Rose Gold', 'Rose Gold'), ('Saudi Gold', 'Saudi Gold'), ('Japan Gold', 'Japan Gold'), ('Tri-Color', 'Tri-Color')], default='White Gold', max_length=20, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawn',
            name='grams',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Grams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawn',
            name='item_description',
            field=models.CharField(choices=[('Anklet', 'Anklet'), ('Bangle', 'Bangle'), ('Bracelet', 'Bracelet'), ('Stud Earrings', 'Stud Earrings'), ('Loop Earrings', 'Loop Earrings'), ('Clip Earrings', 'Clip Earrings'), ('Stud Earrings', 'Stud Earrings'), ('Dangling Earrings', 'Dangling Earrings'), ('Ring', 'Ring'), ('Wedding Ring', 'Wedding Ring'), ('Necklace', 'Necklace'), ('Pendant', 'Pendant')], default='Ring', max_length=20, verbose_name='Item Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawn',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='historicalpawn',
            name='description',
            field=models.TextField(verbose_name='Additional Description'),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='description',
            field=models.TextField(verbose_name='Additional Description'),
        ),
    ]
