# Generated by Django 4.0 on 2024-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0013_historicalpawn_carat_historicalpawn_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrequests',
            name='interest_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Interest Due'),
            preserve_default=False,
        ),
    ]
