# Generated by Django 4.0 on 2024-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0014_discountrequests_interest_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='advance_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Advance Interest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Interest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Penalty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service Fee'),
            preserve_default=False,
        ),
    ]
