# Generated by Django 4.0 on 2024-05-06 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0016_alter_historicalpawn_carat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpawn',
            name='appraised_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Appraised Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpawn',
            name='promised_renewal_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Promised Renewal Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpawn',
            name='transaction_type',
            field=models.CharField(choices=[('NEW', 'New'), ('EXISTING', 'Existing')], default='NEW', max_length=10, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='pawn',
            name='appraised_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Appraised Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawn',
            name='promised_renewal_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Promised Renewal Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawn',
            name='transaction_type',
            field=models.CharField(choices=[('NEW', 'New'), ('EXISTING', 'Existing')], default='NEW', max_length=10, verbose_name='Transaction Type'),
        ),
    ]
