# Generated by Django 4.0 on 2024-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0017_historicalpawn_appraised_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpawn',
            name='additional_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Additional Principal'),
        ),
        migrations.AddField(
            model_name='pawn',
            name='additional_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Additional Principal'),
        ),
    ]
