# Generated by Django 4.0 on 2024-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0018_historicalpawn_additional_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_granted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Granted'),
        ),
    ]
