# Generated by Django 4.0 on 2024-06-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0020_historicalpawn_on_hold_pawn_on_hold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpawn',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pawn',
            name='date',
        ),
        migrations.AddField(
            model_name='historicalpawn',
            name='date_granted',
            field=models.DateField(blank=True, null=True, verbose_name='Date granted'),
        ),
        migrations.AddField(
            model_name='pawn',
            name='date_granted',
            field=models.DateField(blank=True, null=True, verbose_name='Date granted'),
        ),
    ]
