# Generated by Django 4.0 on 2024-08-12 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0022_alter_historicalpawn_carat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpawn',
            name='date_encoded',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Date encoded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawn',
            name='date_encoded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date encoded'),
            preserve_default=False,
        ),
    ]
