# Generated by Django 4.0 on 2024-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0023_historicalpawn_date_encoded_pawn_date_encoded'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpawn',
            name='renew_redeem_date',
            field=models.DateField(blank=True, null=True, verbose_name='Renew/Redeem Date'),
        ),
        migrations.AddField(
            model_name='pawn',
            name='renew_redeem_date',
            field=models.DateField(blank=True, null=True, verbose_name='Renew/Redeem Date'),
        ),
    ]
