# Generated by Django 4.0 on 2024-10-15 00:35

from django.db import migrations, models
import pawn.models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0024_historicalpawn_renew_redeem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpawn',
            name='date_granted',
            field=models.DateField(blank=True, null=True, validators=[pawn.models.validate_date_granted], verbose_name='Date granted'),
        ),
        migrations.AlterField(
            model_name='historicalpawn',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RENEWED', 'Renewed'), ('REDEEMED', 'Redeemed'), ('AUCTIONED', 'Auctioned'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='date_granted',
            field=models.DateField(blank=True, null=True, validators=[pawn.models.validate_date_granted], verbose_name='Date granted'),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RENEWED', 'Renewed'), ('REDEEMED', 'Redeemed'), ('AUCTIONED', 'Auctioned'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
    ]
