# Generated by Django 4.0 on 2024-10-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0025_alter_historicalpawn_date_granted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawn',
            name='renewed_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_renewed_to', to='pawn.pawn'),
        ),
    ]
