# Generated by Django 4.0 on 2024-12-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0027_alter_payment_advance_interest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-pawn__pk']},
        ),
        migrations.AddField(
            model_name='historicalpawn',
            name='pawn_ticket_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Pawn Ticket Number'),
        ),
        migrations.AddField(
            model_name='pawn',
            name='pawn_ticket_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Pawn Ticket Number'),
        ),
    ]
