# Generated by Django 4.0 on 2025-02-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0028_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpawn',
            name='pawn_ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pawn Ticket Number'),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='pawn_ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pawn Ticket Number'),
        ),
    ]
