# Generated by Django 4.0 on 2025-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0029_alter_historicalpawn_pawn_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
