# Generated by Django 4.0 on 2026-03-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0030_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpawn',
            name='transaction_type',
            field=models.CharField(choices=[('ACC', 'Accrued Interest'), ('ADV', 'Advance Interest')], default='ACC', max_length=10, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='transaction_type',
            field=models.CharField(choices=[('ACC', 'Accrued Interest'), ('ADV', 'Advance Interest')], default='ACC', max_length=10, verbose_name='Transaction Type'),
        ),
    ]
