# Generated by Django 4.0 on 2026-03-20 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0031_alter_historicalpawn_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpawn',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 20, 16, 44, 29, 232722), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawn',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
