# Generated by Django 4.0 on 2024-05-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0016_remove_otherfees_advance_interest_rate'),
        ('access_hub', '0003_alter_employee_branch_alter_employee_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance_coh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_cib', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_in_bank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_positions', to='files.branch')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_positions', to='access_hub.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LessDisbursements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payee', models.CharField(blank=True, max_length=50, null=True)),
                ('particulars', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_cash_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='reports.dailycashposition')),
            ],
        ),
        migrations.CreateModel(
            name='AddReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True)),
                ('received_from', models.CharField(blank=True, max_length=50, null=True)),
                ('particulars', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_cash_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reports.dailycashposition')),
            ],
        ),
    ]
