# Generated by Django 4.0 on 2024-05-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycashposition',
            name='balance_cib',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailycashposition',
            name='balance_coh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailycashposition',
            name='cash_in_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailycashposition',
            name='deposits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailycashposition',
            name='withdrawals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
