# Generated by Django 4.0 on 2024-05-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_cashcount_othercashcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreceipts',
            name='automated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessdisbursements',
            name='automated',
            field=models.BooleanField(default=False),
        ),
    ]
