# Generated by Django 4.0 on 2024-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_addreceipts_automated_lessdisbursements_automated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreceipts',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lessdisbursements',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
