# Generated by Django 4.0 on 2024-06-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_hub', '0003_alter_employee_branch_alter_employee_user_type'),
        ('reports', '0005_alter_addreceipts_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycashposition',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_positions', to='access_hub.employee'),
        ),
    ]
