# Generated by Django 4.0 on 2024-10-15 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_hub', '0003_alter_employee_branch_alter_employee_user_type'),
        ('reports', '0006_alter_dailycashposition_prepared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcount',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='access_hub.employee'),
        ),
    ]
