# Generated by Django 4.0 on 2024-10-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_addreceipts_pawn_lessdisbursements_pawn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addreceipts',
            options={'verbose_name': 'Add Receipt', 'verbose_name_plural': 'Add Receipts'},
        ),
        migrations.AlterModelOptions(
            name='lessdisbursements',
            options={'verbose_name': 'Less Disbursement', 'verbose_name_plural': 'Less Disbursements'},
        ),
    ]
