# Generated by Django 4.0 on 2024-05-14 20:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_hub', '0003_alter_employee_branch_alter_employee_user_type'),
        ('files', '0016_remove_otherfees_advance_interest_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 14))])),
                ('encoded_on', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='files.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='files.expensecategory')),
                ('encoded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_encoded', to='access_hub.employee')),
            ],
        ),
    ]
