# Generated by Django 4.0 on 2026-06-29 08:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0020_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2026, 6, 29))]),
        ),
    ]
