# Generated by Django 4.0 on 2024-02-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cashier'), (2, 'Staff'), (3, 'Expense Personnel'), (4, 'Administrator')], default=1),
        ),
    ]
