# Generated by Django 4.0 on 2023-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='category',
            field=models.CharField(max_length=20, unique=True, verbose_name='Category'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('last_name', 'first_name', 'middle_name')},
        ),
    ]
