# Generated by Django 4.0 on 2023-11-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_branch_name_alter_expensecategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='days_open',
            field=models.CharField(max_length=50, verbose_name='Days Open'),
        ),
    ]
