# Generated by Django 4.0 on 2023-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_branch_days_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Service Fee')),
                ('advance_interest_rate', models.PositiveSmallIntegerField(verbose_name='Advance Interest Rate (in percent)')),
            ],
        ),
        migrations.DeleteModel(
            name='AdvanceInterestRate',
        ),
        migrations.DeleteModel(
            name='ServiceFee',
        ),
    ]
