# Generated by Django 4.0 on 2023-11-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_otherfees_delete_advanceinterestrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherfees',
            name='advance_interest_rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Advance Interest Rate (in percent)'),
        ),
        migrations.AlterField(
            model_name='otherfees',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Service Fee'),
        ),
    ]
