# Generated by Django 4.0 on 2023-11-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_otherfees_advance_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity', models.PositiveSmallIntegerField(default=0, verbose_name='Days before Maturity')),
                ('expiration', models.PositiveSmallIntegerField(default=0, verbose_name='Days before Expiration')),
            ],
        ),
        migrations.DeleteModel(
            name='Expiration',
        ),
        migrations.DeleteModel(
            name='Maturity',
        ),
    ]
