# Generated by Django 4.0 on 2023-11-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_termduration_delete_expiration_delete_maturity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestrate',
            name='max_day',
        ),
    ]
