# Generated by Django 4.0 on 2024-02-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_client_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['category'], 'verbose_name_plural': 'Expense categories'},
        ),
    ]
