# Generated by Django 4.0 on 2024-02-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_branch_options_alter_expensecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestrate',
            options={'ordering': ['min_day']},
        ),
        migrations.RemoveField(
            model_name='interestrate',
            name='approval_required',
        ),
    ]
