# Generated by Django 4.0 on 2024-02-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_alter_interestrate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='ID Type')),
            ],
            options={
                'verbose_name': 'Valid ID',
                'verbose_name_plural': 'Valid ID',
                'ordering': ['type'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='id_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenters', to='files.validid'),
        ),
    ]
