# Generated by Django 4.0 on 2024-02-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_validid_client_id_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validid',
            options={'ordering': ['type'], 'verbose_name': 'Valid ID', 'verbose_name_plural': 'Valid IDs'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_presented',
        ),
        migrations.AlterField(
            model_name='client',
            name='id_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenters', to='files.validid', verbose_name='Presented ID'),
        ),
    ]
