# Generated by Django 4.0 on 2024-05-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_client_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceInterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.PositiveSmallIntegerField(verbose_name='Interest Rate')),
                ('min_day', models.PositiveSmallIntegerField(verbose_name='Minimum Days')),
            ],
            options={
                'ordering': ['min_day'],
            },
        ),
    ]
