# Generated by Django 4.0 on 2024-09-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_remove_otherfees_advance_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfees',
            name='penalty_rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Penalty Rate'),
        ),
    ]
